package: numba
platform:
    - osx-64
    - linux-32
    - linux-64
    - win-32
    - win-64
engine:
    - python=2.6 numpy=1.9
    - python=2.7 numpy=1.10
    - python=3.4 numpy=1.10
    - python=3.5 numpy=1.10
script:
    - python buildscripts/my_conda_build.py -c numba buildscripts/condarecipe.local --no-anaconda-upload

---
# CUDA machines
platform:
    - linux-64-cuda
engine:
    - python=2.7 numpy=1.10
    - python=3.4 numpy=1.10
script:
    - export HAS_CUDA=1
    - python buildscripts/my_conda_build.py -c numba buildscripts/condarecipe.local --no-anaconda-upload

---
# HSA machines
platform:
    - linux-64-hsa-kaveri
    - linux-64-hsa-dgpu
engine:
    - python=2.7 numpy=1.10
    - python=3.4 numpy=1.10
script:
    - export HAS_HSA=1
    - python buildscripts/my_conda_build.py -c numba buildscripts/condarecipe.local --no-anaconda-upload
